services:
  db:
    image: postgres:13
    container_name: dashboard_management_db_testing
    environment:
      POSTGRES_USER: ming_group
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dashboard_management
    volumes:
      - pg_data:/var/lib/postgresql/data
      - /Users/db_backups/db_dump.sql:/docker-entrypoint-initdb.d/init.sql  # Host to container file mapping
      - /Users/db_backups:/docker-entrypoint-initdb.d/db_backups  # Absolute path for db backups
    ports:
      - "5432:5432"
    # Healthcheck to wait for DB to be ready
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ming_group", "-d", "dashboard_management"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  web:
    image: anirudhchawla889/ming_group_dashboard:latest  # Your Django app image
    environment:
      DATABASE_URL: postgres://user:password@db:5432/dashboard_management
    ports:
      - "8000:8000"
    volumes:
      - /app/staticfiles  # Mounting the static directory
    depends_on:
      - db  # Ensure db starts before Django

  nginx:
    image: nginx:latest
    container_name: my_nginx_testing
    volumes:
      - ./nginx/dashboardManagement_no_passphrase.key:/etc/nginx/cert/dashboardManagement.key
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx:/etc/nginx/cert
      - ./staticfiles:/app/staticfiles:rw
    ports:
      - "443:443"
      - "80:80"  # Redirect HTTP to HTTPS
    depends_on:
      - web

volumes:
  pg_data:


