error_log /Users/anirudhchawla/Downloads/dashboardManagement/logs/error.log error;

worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 443 ssl;
        server_name 0.0.0.0;

        ssl_certificate /Users/anirudhchawla/Downloads/dashboardManagement/nginx/self-signed-certificate.pem;
        ssl_certificate_key /Users/anirudhchawla/Downloads/dashboardManagement/nginx/self-signed-key.pem;

        location / {
            proxy_pass http://127.0.0.1:8001;  # Forward requests to Django on port 8001 (HTTP)
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
            alias /Users/anirudhchawla/Downloads/dashboardManagement/static/;
        }

    }

}
