"""
Django settings for dashboardManagement project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import re
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+$449&c$rp!ovz7)+%al4s8qrblqm(rji23)vl672^0crxydy^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', 'ming-dashboard.zapto.org', '100.112.78.57','0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'invoice',
    'sepa_generator_for_invoice',
    'social_django',
    'django_extensions',
    'users',
    'dashboard'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dashboardManagement.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  # Required for social auth
                'social_django.context_processors.login_redirect', 
            ],
        },
    },
]

WSGI_APPLICATION = 'dashboardManagement.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'dashboard_management',
        'USER': 'ming_group',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Add this if you have a 'static' directory in your project root
#STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, 'static'),
#]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Set the authentication backends
AUTHENTICATION_BACKENDS = (
    'social_core.backends.slack.SlackOAuth2',  # Add Slack backend
    'django.contrib.auth.backends.ModelBackend',  # Default authentication
)

# OAuth keys from Slack
SOCIAL_AUTH_SLACK_KEY = os.getenv("SOCIAL_AUTH_SLACK_KEY")
SOCIAL_AUTH_SLACK_SECRET = os.getenv("SOCIAL_AUTH_SLACK_SECRET")

# Redirect URLs
LOGIN_REDIRECT_URL = '/invoice/dashboard/'
SOCIAL_AUTH_SLACK_SCOPE = ['identity.basic', 'identity.email', 'identity.avatar']  # Adjust as needed
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SOCIAL_AUTH_SLACK_REDIRECT_URI = 'https://89.247.170.204/accounts/complete/slack/'
TIME_ZONE = 'Europe/Berlin'

USE_TZ = True  # This enables Django's timezone support

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

SECURE_SSL_REDIRECT = True  # Redirect HTTP to HTTPS automatically
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = [
    'https://localhost',
    'https://0.0.0.0',
    'https://100.112.78.57:8000',
    'https://ming-dashboard.zapto.org:8000',
    'https://24ba-87-140-14-143.ngrok-free.app',  # Regex pattern for all ngrok subdomains
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    'https://localhost',
    'https://0.0.0.0',
    'https://100.112.78.57:8000',
    'https://ming-dashboard.zapto.org:8000',
    'https://24ba-87-140-14-143.ngrok-free.app',
]

CORS_ORIGIN_WHITELIST = [
    'https://localhost',
    'https://0.0.0.0',
    'https://100.112.78.57:8000',
    'https://ming-dashboard.zapto.org:8000',
    'https://24ba-87-140-14-143.ngrok-free.app',
]