# Generated by Django 4.2.16 on 2024-11-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='bic',
            field=models.CharField(blank=True, default='', max_length=34),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=34),
        ),
    ]
