name: Deploy to MacBook Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Print SSH host
      run: |
        echo "SSH Host is: ${{ secrets.SSH_HOST }}"

    - name: Deploy to server
      run: |
        sudo -S ssh apple@192.168.0.10 'cd Downloads/ming_group_projects/dashboardManagement && sudo -S git pull origin main'
